#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Allow Nginx through the firewall
sudo ufw allow 'Nginx Full'

# Add custom header configuration to Nginx
sudo bash -c 'cat <<EOF > /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Custom HTTP response header
    add_header X-Served-By \$hostname;
}
EOF'

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
